### ISSUE TITLE
Try version plugin

### ISSUE THREAD

**Issue by bstansberry** [bstansberry/wildfly-snapshot-ci#1]
```
name: version plugin
env:
  # We can set env vars which will get used by the resulting workflow
  MY_VAR: Hello!!
components:
  - name: jboss-parent-pom
    org: jboss
    branch: 'master'
    mavenOpts: -DskipTests
  - name: jboss-remoting
    org: jboss-marshalling
    branch: 'main'
    mavenOpts: versions:update-parent -DallowSnapshots=true
```
