### ISSUE TITLE
Try version plugin

### ISSUE THREAD

**Issue by bstansberry** [bstansberry/wildfly-snapshot-ci#3]
```
name: version plugin
env:
  # We can set env vars which will get used by the resulting workflow
  MY_VAR: Hello0
  MAVEN_SETUP_CMD: versions:update-parent -DallowSnapshots=true
  #JBOSS_MARSHALLING_MAVEN_EXTRA_PARAMS: -DskipTests
components:
  - name: jboss-parent-pom
    org: jboss
    branch: 'main'
    mavenOpts: -DskipTests
  - name: jboss-marshalling
    org: jboss-remoting
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: jboss-remoting
    org: jboss-remoting
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: xnio
    org: xnio
    branch: '3.x'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: undertow
    org: undertow-io
    branch: 'master'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: jboss-modules
    org: jboss-modules
    branch: '2.x'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: wildfly-arquillian
    org: wildfly
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: wildfly-maven-plugin
    org: wildfly
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: galleon-plugins
    org: wildfly
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: quickstart
    org: wildfly
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: wildfly-core
    org: wildfly
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
  - name: wildfly
    org: wildfly
    branch: 'main'
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
```
